version: "3.2"
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.2.5-enterprise 
    volumes: 
      - ./neo4j/data:/data'
      - ./neo4j/plugins/:/plugins/'
      #- ./neo4j/import/:/var/lib/neo4j/import'
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/neo
      - NEOJLABS_PLUGINS=["apoc", "graph-data-science"]  
    restart: on-failure    
    networks: 
      - neo4j_go_net
    command: neo4j 

networks:
  neo4j_go_net:
    driver: bridge

volumes:
  dgraph:

