version: "3.2"
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.2 
    volumes: 
      - ./neo4j/data:/data'
      - ./neo4j/conf/:/conf/'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    networks: 
      - neo4j_go_net
    command: neo4j 

networks:
  neo4j_go_net:
    driver: bridge

volumes:
  dgraph:

